import type { Metadata } from "next";
import { Archivo, Chivo_Mono } from 'next/font/google';
import "./globals.css";
import Navbar from "./_components/Navbar";

const archivo = Archivo({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
});

const chivoMono = Chivo_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-chivo-mono',
});

export const metadata: Metadata = {
  title: "N7 - New foundation of modern banking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.className} ${chivoMono.variable} h-full antialiased bg-[#000D12] text-[#E9F4F9] overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
